// Shared helpers for the npm scripts.
import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

export const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
export const PY = path.join(ROOT, ".venv/bin/python");
export const FPS = 30, PAD = 0.3, TRANS = 9, MAX = 180;

export const videoDir = (slug) => path.join(ROOT, "videos", slug);
export const loadVideo = (slug) => {
  const spec = JSON.parse(fs.readFileSync(path.join(videoDir(slug), "video.json"), "utf8"));
  const tp = path.join(videoDir(slug), "build/timings.json");
  const timings = fs.existsSync(tp) ? JSON.parse(fs.readFileSync(tp, "utf8")) : null;
  return { spec, timings };
};

/** Same maths as engine/core/durations.ts */
export const layout = (spec, timings, part) => {
  const ids = spec.parts[part];
  const scenes = ids.map((id) => spec.scenes.find((s) => s.id === id));
  const frames = scenes.map((s) => Math.ceil((s.silentSeconds ?? (timings[s.id]?.duration ?? 3) + PAD) * FPS));
  const starts = frames.reduce((a, f, i) => (a.push(i === 0 ? 0 : a[i - 1] + frames[i - 1] - TRANS), a), []);
  const total = frames.reduce((a, b) => a + b, 0) - TRANS * (ids.length - 1);
  return { ids, frames, starts, total };
};

/** Writes engine/registry.generated.ts so Root.tsx can import every voiced video. */
export const genRegistry = () => {
  const slugs = fs.readdirSync(path.join(ROOT, "videos")).filter((s) => fs.existsSync(path.join(videoDir(s), "build/timings.json")));
  const lv = path.join(ROOT, "public/music/levels.json");
  const levels = fs.existsSync(lv) ? fs.readFileSync(lv, "utf8") : "{}";
  const lines = ["// GENERATED by scripts/lib/common.mjs. Do not edit.", 'import { Timings, VideoSpec } from "./types";'];
  slugs.forEach((s, i) => lines.push(`import v${i} from "../videos/${s}/video.json";`, `import t${i} from "../videos/${s}/build/timings.json";`));
  lines.push(`export const VIDEOS: { spec: VideoSpec; timings: Timings }[] = [${slugs.map((_, i) => `{ spec: v${i} as unknown as VideoSpec, timings: t${i} as Timings }`).join(", ")}];`);
  lines.push(`export const MUSIC_LEVELS: Record<string, number> = ${levels.trim()};`);
  fs.writeFileSync(path.join(ROOT, "engine/registry.generated.ts"), lines.join("\n") + "\n");
  return slugs;
};

export const py = (args, opts = {}) => execFileSync(PY, args, { stdio: "inherit", cwd: ROOT, ...opts });
export const compId = (slug, part) => (part === "full" ? slug : `${slug}-${part}`);
